---
- name: Display package versions
  hosts: aap.demo.en1

  become: true
  vars_files:
    - 01_var_packages_new.yml

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Show versions
      ansible.builtin.debug:
        msg: "Package: {{ item }} | Version: {{ ansible_facts.packages[item][0].version | default('not installed') }}"
      loop: "{{ packages }}" 