---
- name: Ensure specific packages are installed at a specific (older) version
  hosts: all
  become: true
  vars:
    packages:
      - name: httpd
        version: 2.4.53-7.el9
      - name: mariadb
        version: 3:10.5.13-2.el9

  tasks:
    - name: Install or downgrade packages to specified versions
      ansible.builtin.dnf:
        name: "{{ item.name }}-{{ item.version }}"
        state: present
        allow_downgrade: yes
      loop: "{{ packages }}"