---
- name: Ensure specific packages are installed at a specific (older) version
  hosts: all
  become: true
  vars_files:
    - 01_var_packages_old.yml

  tasks:
    - name: Install or downgrade packages to specified versions
      ansible.builtin.dnf:
        name: "{{ item.name }}-{{ item.version }}"
        state: present
        allow_downgrade: yes
      loop: "{{ packages }}"