---
- name: Ensure specific packages are installed at a specific (older) version
  hosts: aap.demo.en1
  become: true
  vars_files:
    - 01_var_packages_old.yml

  tasks:
    - name: Install or downgrade packages to specified versions
      ansible.builtin.dnf:
        name: |
          {% for pkg in packages %}
          {{ pkg.name }}-{{ pkg.version }}
          {% endfor %}
        state: present
        allow_downgrade: true
        allowerasing: true  # Required to remove conflicting dependencies