---
- name: Upgrade all packages to the latest version
  hosts: all
  become: true

  tasks:
    - name: Upgrade all packages to latest
      ansible.builtin.dnf:
        name: "*"
        state: latest