---
- name: Show firewall status and open ports
  hosts: all
  become: yes
  tasks:
    - name: Gather firewall facts
      ansible.posix.firewalld_info:
        zones: yes
        services: yes
        ports: yes
      register: firewall_facts

    - name: Check if firewalld is running
      ansible.builtin.service_facts:
      register: service_status

    - name: Display firewall status
      ansible.builtin.debug:
        msg: |
          Firewalld Status: {{ 'Running' if service_status.ansible_facts.services['firewalld.service'].state == 'running' else 'Stopped' }}
          Default Zone: {{ firewall_facts.firewalld.default_zone }}
          
          Open Ports:
          {% for zone in firewall_facts.firewalld.zones %}
          Zone: {{ zone }}
            Ports: {{ firewall_facts.firewalld.zones[zone].ports | default('None') }}
            Services: {{ firewall_facts.firewalld.zones[zone].services | default('None') }}
          {% endfor %}