---
- name: Show complete firewall port configuration
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - firewalld
          - python3-firewall
        state: present
      when: ansible_os_family == 'RedHat'

    - name: permanently enable firewalld service, also enable it immediately if possible
      ansible.posix.firewalld:
        service: firewalld
        state: enabled
        permanent: true
        immediate: true
        offline: true

    - name: Gather firewalld configuration
      ansible.posix.firewalld_info:
        active_zones: yes
      register: firewalld_info

    - name: Output open ports per zone
      ansible.builtin.debug:
        msg: |
          {% for zone, details in firewalld_info.firewalld_info.zones.items() %}
          Zone: {{ zone }}
            Ports: {{ details.ports | default('None') }}
            Services: {{ details.services | default('None') }}
          {% endfor %}