---
- name: Show complete firewall port configuration
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - firewalld
          - python3-firewall
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Gather full firewall facts
      ansible.posix.firewalld_info:
        active_zones: yes
        zones: all
        services: yes
        ports: yes
        rich_rules: yes
      register: firewall_info