---
- name: Enable ports and show firewall port information
  hosts: all
  become: true
  vars_files:
    - 03_define_ports.yml

  tasks:
    - name: Permit traffic in default zone on ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ demo_ports_enable }}"

    - name: Reload firewalld to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Gather firewalld configuration
      ansible.posix.firewalld_info:
        active_zones: yes
      register: firewalld_info

    - name: Output open ports per zone
      ansible.builtin.debug:
        msg: |
          {% for zone, details in firewalld_info.firewalld_info.zones.items() %}
          Zone: {{ zone }}
            Ports: {{ details.ports | default('None') }}
            Services: {{ details.services | default('None') }}
          {% endfor %}