---
- name: Enable ports and show firewall port information
  hosts: all
  become: true
  vars:
    demo_ports:
      - 80/tcp    # HTTP
      - 443/tcp   # HTTPS
      - 8080/tcp  # Custom demo port
      - 8081/tcp

  tasks:
    - name: Permit traffic in default zone on ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ demo_ports }}"

    - name: Reload firewalld to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Gather firewalld configuration
      ansible.posix.firewalld_info:
        active_zones: yes
      register: firewalld_info

    - name: Output open ports per zone
      ansible.builtin.debug:
        msg: |
          {% for zone, details in firewalld_info.firewalld_info.zones.items() %}
          Zone: {{ zone }}
            Ports: {{ details.ports | default('None') }}
            Services: {{ details.services | default('None') }}
          {% endfor %}