---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ansible-builder-rhel9:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

options:
  package_manager_path: /usr/bin/microdnf                                                                       