---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ansible-builder-rhel9:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

      #additional_build_steps:
  #append_base:
  # - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11                                                                          