---
- name: Revert RAID10 and LVM setup
  hosts: raid10target
  become: true
  vars_files:
    - 02_raid_config.yml

  tasks:
    - name: Unmount data LV
      mount:
        path: "{{ mount_point_data }}"
        state: unmounted
        fstype: ext4
        src: "/dev/{{ vg_name }}/{{ lv_data_name }}"

    - name: Unmount backup LV
      mount:
        path: "{{ mount_point_backup }}"
        state: unmounted
        fstype: ext4
        src: "/dev/{{ vg_name }}/{{ lv_backup_name }}"

    - name: Remove mount point directory
      file:
        path: "{{ mount_point_data }}"
        state: absent
    - name: Remove backup mount point directory
      file:
        path: "{{ mount_point_backup }}"
        state: absent
    - name: Remove logical volume
      command: lvremove -y /dev/{{ vg_name }}/{{ lv_data_name }}
      ignore_errors: true

    - name: Remove backup logical volume
      command: lvremove -y /dev/{{ vg_name }}/{{ lv_backup_name }}
      ignore_errors: true

    - name: Remove volume group
      command: vgremove -y {{ vg_name }}
      ignore_errors: true

    - name: Remove physical volume
      command: pvremove -y {{ raid_device }}
      ignore_errors: true

    - name: Stop RAID device
      command: mdadm --stop {{ raid_device }}
      ignore_errors: true

    - name: Remove RAID device (only if present)
      command: mdadm --remove {{ raid_device }}
      when: raid_device_exists.stat.exists
      ignore_errors: true
      register: remove_raid_result
      failed_when: false

    - name: Check if RAID device exists
      stat:
        path: "{{ raid_device }}"
      register: raid_device_exists
      ignore_errors: true

    - name: Zero superblocks on RAID member devices
      command: mdadm --zero-superblock --force {{ item }}
      loop: "{{ raid_devices }}"

    - name: Remove mdadm config file
      file:
        path: /etc/mdadm/mdadm.conf
        state: absent
    - name: Remove data and backup mount entries from /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: "^/dev/{{ vg_name }}/"
        state: absent
